version: '3.7'

services:
  traefik:
    image: traefik:v2.4
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:3000"
      - "--entrypoints.ping.address=:8082"
      - "--ping.entryPoint=ping"
    ports:
      - "3000:3000"
      - "8080:8080"
      - "8082:8082"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  defi-blockchain:
    image: defi/defichain:1.7.9-rc.1
    command: >
      defid
      -printtoconsole
      -rpcallowip=0.0.0.0/0
      -rpcbind=0.0.0.0
      -rpcuser=playground-rpcuser
      -rpcpassword=playground-rpcpassword
      -masternode_operator=mswsMVsyGMj1FzDMbbxw2QW3KvQAv2FKiy
      -regtest=1
      -txnotokens=0
      -logtimemicros
      -txindex=1
      -acindex=1
      -amkheight=0
      -bayfrontheight=1
      -bayfrontgardensheight=2
      -clarkequayheight=3
      -dakotaheight=4
      -dakotacrescentheight=5
      -eunosheight=6

  defi-playground:
    build: ..
    image: ghcr.io/defich/playground:latest
    depends_on:
      - defi-blockchain
    ports:
      - "3001:3000"
    environment:
      PLAYGROUND_DEFID_URL: http://playground-rpcuser:playground-rpcpassword@defi-blockchain:19554
    labels:
      - "traefik.http.services.playground.loadbalancer.server.port=3000"
      - "traefik.http.routers.playground.priority=0"
      - "traefik.http.routers.playground.rule=PathPrefix(`/{version:v[1-9]}/playground/rpc/`, `/{version:v[1-9]}/playground/wallet`, `/{version:v[1-9]}/playground/info`)"
      - "traefik.http.routers.playground.entrypoints=web"

  defi-whale:
    image: ghcr.io/defich/whale:latest
    depends_on:
      - defi-blockchain
    ports:
      - "3002:3000"
    environment:
      WHALE_DEFID_URL: http://playground-rpcuser:playground-rpcpassword@defi-blockchain:19554
      WHALE_DATABASE_PROVIDER: memory
      WHALE_NETWORK: regtest
    labels:
      - "traefik.http.services.whale.loadbalancer.server.port=3000"
      - "traefik.http.routers.whale.priority=1"
      - "traefik.http.routers.whale.rule=PathPrefix(`/v1/playground/`)"
      - "traefik.http.routers.whale.entrypoints=web"
      - "traefik.http.routers.playground.middlewares=rewrite"
      - "traefik.http.middlewares.rewrite.replacepathregex.regex=^/v1/playground/(.*)"
      - "traefik.http.middlewares.rewrite.replacepathregex.replacement=/v1/regtest/$$1"
